<a href='https://github.com/angular/angular.js/edit/v1.8.x/docs/content/error/$timeout/badprom.ngdoc?message=docs(error%2Fbadprom)%3A%20describe%20your%20change...' class='improve-docs btn btn-primary'><i class="glyphicon glyphicon-edit">&nbsp;</i>Improve this Doc</a>


<h1>Error: $timeout:badprom
  <div><span class='hint'>Non-$timeout promise</span></div>
</h1>

<div>
    <pre class="minerr-errmsg" error-display="`$timeout.cancel()` called with a promise that was not generated by `$timeout()`.">`$timeout.cancel()` called with a promise that was not generated by `$timeout()`.</pre>
</div>

<h2 id="description">Description</h2>
<div class="description">
  <p>This error occurs when calling <a href="api/ng/service/$timeout#cancel">$timeout.cancel()</a> with a promise that
was not generated by the <a href="api/ng/service/$timeout">$timeout</a> service. This can, for example, happen when
calling <a href="api/ng/service/$q#the-promise-api">then()/catch()</a> on the returned promise, which creates a new
promise, and pass that new promise to <a href="api/ng/service/$timeout#cancel">$timeout.cancel()</a>.</p>
<p>Example of incorrect usage that leads to this error:</p>
<pre><code class="lang-js">var promise = $timeout(doSomething, 1000).then(doSomethingElse);
$timeout.cancel(promise);
</code></pre>
<p>To fix the example above, keep a reference to the promise returned by
<a href="api/ng/service/$timeout">$timeout()</a> and pass that to <a href="api/ng/service/$timeout#cancel">$timeout.cancel()</a>:</p>
<pre><code class="lang-js">var promise = $timeout(doSomething, 1000);
var newPromise = promise.then(doSomethingElse);
$timeout.cancel(promise);
</code></pre>

</div>


